#!/bin/zsh

# Backups a instance of a firestore database.
#
# $1 - Project Name
# $2 - Cloud Storage Location

fsbackup() {
  echo "Backing up database($1) to $2"
  gcloud firestore --project $1 export $2
}